project:
  type: website
  output-dir: docs

website:
  title: "Evan Perry"
  favicon: "images/icon.png"

format:
  html:
    theme: 
      - custom.scss
    fontsize: 1rem
    fontcolor: "#666666"
    linkcolor: "#506C64"
    css: styles.css
    toc: false

editor: visual