project:
  type: website
  output-dir: docs

website:
  title: "Evan Perry"
  favicon: "images/icon.png"
  navbar:
    left:
      - href: index.qmd
        text: Bio
      - href: research.qmd
        text: "Research & Writing" 
      - href: data.qmd
        text: "Data & Software"

format:
  html:
    theme: 
      - mint
      - custom.scss
    fontsize: 1.1rem
    fontcolor: "#666666"
    linkcolor: "#381D2A"
    css: styles.css
    toc: false

editor: visual